### ISSUE TITLE
Add question group headers to the dashboard filters

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#262]
To make the filters more readable, we would like to add the question group headers from LS to hte filter display and group the questions accordingly.

**Comment by SamMousa** [comment]
Filtering would need to be reimplemented, but it can be done.

**Comment by SamMousa** [comment]
This is actually what we had originally and it was then removed. Currently you can use the search feature and it will also search in the group name.
If this is needed please assign to @jeremiehelme so he can create a mockup.

FYI the implementation is simpler than I thought because we actually have the group name available as we use it for searching in the filters.

**Comment by SamMousa** [comment]
> If this is needed please assign to @jeremiehelme so he can create a mockup.

?

**Comment by jeremiehelme** [comment]
Added question group headers to the filters list

<img width="1680" alt="Capture d’écran 2020-07-27 à 13 40 42" src="https://user-images.githubusercontent.com/2345926/88537955-cd421100-d00e-11ea-9d4d-844bb80b9e7e.png">

**Comment by luna404** [comment]
Re-posting this in the correct issue :)

Looks great, it's much more readable like with the group headers.

There is a lot of white space on the right, could you make the pop-up a less wide so users still see the dashboard in the background?
If you use the search box and hit enter it closes the filter display. Is this on purpose? I think a lot of user might not realize it filters dynamically and hit enter by accident.
