### ISSUE TITLE
Granular workspace management

### ISSUE THREAD

**Issue by SamMousa** [HeRAMS-WHO/herams-backend#296]
> We need the ability to manage project admin permission more granularly. This would mean to split the "Manage workspaces" permissions into individual permissions. Create, edit, delete WS should be added as new individual options (manage data and download data already exists).  

You can already assign permissions to individual workspaces.
If a user has only create permissions then he cannot delete a workspace he just created? He cannot even change its properties.
If we take the logical approach we would then automatically make them admin of the workspace after they create it, but that will create permissions that can only be revoked and not granted due to #294 

Which role needs this permission? Please create issues for the individual roles that need this, describe the roles and put the issue numbers in this thread.

**Comment by SamMousa** [comment]
@SamuelPetragallo @luna404

**Comment by SamuelPetragallo** [comment]
@SamMousa yes in most cases these 3 permissions  (create, edit properties, delete) will be assigned as a bundle, but after discussing that we decided to have them separate regardless to prevent any possible issue and considering that the additional workload of assigning 3 permissions instead of one is minimal. An example would be a new Project Admin that would need to create new workspaces (e.g. to onboard newly arrived NGOs ) but that we (or other owners/admin locally) fear may mess up with existing WS already in prod.

**Comment by SamMousa** [comment]
This new admin would then not be able to do anything to those new WS

**Comment by SamuelPetragallo** [comment]
Beyond creating and editing properties. But yes, I agree those are very tightly linked, but again since the cost of assigning both separately is so low, we decided to keep them separate, a bit like in ls basically:

![image](https://user-images.githubusercontent.com/15345099/73670844-40934780-46aa-11ea-926e-34f59296d476.png)

A lot of those could probably be bundled but the cost of keeping them separate is really low and the risk of not covering a specific case null

**Comment by SamMousa** [comment]
Editing properties is not included since that is a different permission. Also creating a WS will lock the token to that WS and thus not allow them to correct a mistake by removing the WS
