### ISSUE TITLE
Super-share permissions

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#302]
If I understood correctly, only global admin can grant super share permission. This means that global admins could grant super-share permissions to WS owners but not Project Admins. In my opinion, there should be no difference in the level of permissions that theses two roles can grant at the workspace level. This would mean, either project admins can grant super-share permissions of a workspace or there should be no possibility to do this at all.

**Comment by SamMousa** [comment]
Assigning someone the `manage workspaces` permission gives them full admin privileges on the workspaces. So that should allow them to assign any permission.

**Comment by SamMousa** [comment]
I think you're right and I'm missing a business rule.
Anyone with full admin permissions on an object should be able to assign any permission to it.

**Comment by SamMousa** [comment]
This now works on staging.
Note that implementing #296 would break this again.

Since we split `manage` into `create`, `update` and `delete` but do not have the option `admin` due to #294 you will not be able to assign a permission to a project admin that allows them to grant super share for the project or any of its workspaces.

**Comment by luna404** [comment]
Thanks, it's working.

I'm not sure I understand the issue. As a `global admin` i can grant a user access to `create`, `update` 
 and `delete` workspace. Together with the `share` permission they will be able to grant other users access. Now with the `super-share` shouldn't they also be able to share the share permissions?

Maybe can you explain what is included in the `manage` permission. I thought it was just `create`, `edit` and `delete`. if there are other missing bundled into this, they should of course also be added as individual permissions.

**Comment by SamMousa** [comment]
Manage workspaces grants them admin privileges to all existing workspaces in the project as well as permission to create new workspaces in the project.

**Comment by luna404** [comment]
As we keep having different definitions of what admin means. What does admin mean in this case? They can create, edit and delete data, modify and download data and share access to workspaces?

**Comment by SamMousa** [comment]
> As we keep having different definitions of what admin means. 

I have only ever used one definition, i'll repeat it again:
When a user X has `admin` permission on an object Y then this question:
**Can user X do operation Z to Y** will always be true.

This is different, and most importantly, totally unrelated to the admin roles that you have defined.

**Comment by SamuelPetragallo** [comment]
Quick chip in here: I can't think of another term to cover what we intend as admin on the business/process-side, and I guess it would be the same for a lot of our users, but since this is a recurrent source of misunderstanding could we use a different term for the tech side @SamMousa that works for you?

**Comment by SamMousa** [comment]
It does not, the name admin is actually used in the framework as well as third party libraries.
Note that the label of the permission was already **Allow everything** which as far as I can tell does not contain the word `admin` yet it was still confusing.

**Comment by SamuelPetragallo** [comment]
Maybe just keeping the process/business side definition in our discussions and on the frontend part: I understand the term "admin" is used extensively in every area of work, but I'd like that we keep the focus on end users. The framework and 3rd party libraries part of our work is only visible to Jeremie and yourself so hopefully we can make that shift

**Comment by SamMousa** [comment]
> The framework and 3rd party libraries part of our work is only visible to Jeremie and yourself so hopefully we can make that shift

We cannot and really should not want to change those. 

So we end up with the same problem; on the tech side we use logic and clearly defined terms in our communication. On the end user side we are expected to use magic terms without clear definition that should make things so simple that even a 3 year old understands yet powerful enough that it can actually express a complex set of business rules.

This is not realistic.

**Comment by SamuelPetragallo** [comment]
I'm not asking that you change those, I don't even see them. I'd simply like that in our discussions we use ours ;) and I know they can be floating sometimes, but again (ref to my other message) we're dealing with situations (and people) which are imo way more complex than a set of complex business rules can capture... this is the challenge and also the beauty of this work no?

**Comment by SamMousa** [comment]
> I'm not asking that you change those, I don't even see them. I'd simply like that in our discussions we use ours ;) 

I already do this when it is possible, but the defined roles do not cover everything. The only real issue here is the `admin` permission, which apparently is extremely confusing even though there is no role called Admin.
There are roles containing admin like `Global Admin`, `Project Admin` and `Workspace Admin`. I don't get how people get confused since these are clearly different terms. If people cannot read then the assumption that they will be able to know the difference between `Workspace Contributor` and `Workspace Admin` which both contain `Workspace` is also unrealistic.

Back to the original issue:

> This would mean, either project admins can grant super-share permissions of a workspace or there should be no possibility to do this at all.

This is correct, project admins can grant super-share on a workspace. After the first post my reaction clearly specifies this:

> Assigning someone the `manage workspaces` permission gives them full `admin` privileges on the workspaces. So that should allow them to assign any permission.

This is the definition of a project admin and as you can see it has `manage workspaces`.
![image](https://user-images.githubusercontent.com/547021/73840518-9f76cf00-4818-11ea-9390-bcc8bec58cea.png)


Is there anything still unclear about this?

**Comment by SamuelPetragallo** [comment]
Sorry, I think I've added more unnecessary confusion here in my last message.

> > When a user X has `admin` permission on an object Y then this question:
> **Can user X do **operation** Z to Y** will always be true.
> 

What is still unclear to me @SamMousa is what those "operations" are (beyond the ones that are spelled out). Can you give an exhaustive list of those?

**Comment by SamMousa** [comment]
> Do we have an exhaustive list of those?

I do not have a list, I could generate one, but it would be a lot of work and it would quickly be out of date.

I don't get what is so unclear about the word *everything*, it just means that whenever you try to do something the system will allow it. This means it includes future features as well as currently implemented features.

**Comment by luna404** [comment]
Closing this issue for now. We can reopen the discussion on permissions later this once we have a little more experience with the current ones.
