### ISSUE TITLE
Workspaces > Improvements

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#337]
![3 HeRAMs_admin_Project](https://user-images.githubusercontent.com/2345926/74638898-1abb7780-516d-11ea-9c18-15c178dfc96e.jpg)

- Bulk actions would be a good tool for the admins. Especially download, share, delete and refresh actions
- We should keep the actions buttons visible
- Having a list of workspaces we don't have access to would be useful, with a button to ask for permissions, if possible
- Default workspace is to be removed for now (button and home icon)
- A search input would be useful, but is not the most important for now
- Clicking on a row should lead to a new page (a Dashboard for workspaces), which doesn't exists for now)

**Comment by SamMousa** [comment]
> Bulk actions would be a good tool for the admins. Especially download, share, delete and refresh actions

Let's look at these individually:
- Downloading: could be solved by downloading at the project level (optionally leaving out workspaces that one does not have access to)
- Refresh: definitely not, refreshing a single workspace is already troublesome for load times, doing this with multiple will not work. Instead we can do this asynchronously at the workspace / project level. The goal here for people is to NOT use instead of using it more often and in more different ways. At some point we should make this available only to global admins, and after that we should even fully remove the button.
- Share: sharing multiple workspaces can make sense, it will increase the likelihood of errors but I understand the benefit during initial setup. Note that there will be no easy way to unshare for multiple workspaces.
- Delete: can be added, will increase risks of accidentally deleting the wrong thing significantly.

Will these batch actions only support the currently visible rows or all rows? (ie can I delete or share a 1000 workspaces this way or just the ones on a page?)

**Comment by SamMousa** [comment]
> Having a list of workspaces we don't have access to would be useful, with a button to ask for permissions, if possible

The button can be added as soon as we have a flow for requesting permission. We can also have a link to a different page that shows only workspaces without access. It could make more sense to have a search box where people can search for a workspace to request access or a different page for that.
Need to identify the requirements via a user story; how would a user decide he needs / wants access? Are they searching for a specific workspace or just browsing?

**Comment by jeremiehelme** [comment]
This issue need to be discussed

**Comment by luna404** [comment]
As a lot of these points require substantial development and some further discussions. Lets focus on issue #303 first and then see what can be tackled here.

**Comment by luna404** [comment]
See issues #303, #686-#691
