### ISSUE TITLE
Redirect for old login link

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#341]
It seems that with the change in sign-up, the login url also changed. The old link https://herams.org/user/login is no longer working and seems to be replaced with /session/create. As we reference the old link in all our documents and users have it bookmarked like that, would it be possible to do a redirect to the new /session/create page? We will gradually change in all documents, but this will take a while and we have users already reporting this as an error.

**Comment by SamMousa** [comment]
Why is this link in the documents anyway? Any user going to https://herams.org will be redirected to the login page if they need to log in.

Please do not put any direct links in docs, this essentially makes the whole structure very rigid without any benefits.
The proper way is to explain users how to navigate or tell them to bookmark the manual page (so that when the URL structure changes you can update the link in the manual only)

**Comment by SamMousa** [comment]
Update docs to not include deep links.

**Comment by luna404** [comment]
Links are updated, but I'm no longer allowed to commit it myself. Pull request is submitted.

**Comment by jeremiehelme** [comment]
@luna404 I merged your PR but I don't know where to check if it's working

**Comment by SamMousa** [comment]
I'll look at it tomorrow
