### ISSUE TITLE
Data / Overall Backups

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#346]
Let's discuss and see how best that can be approached

**Comment by SamMousa** [comment]
Need to identify the requirements. System-wide backups are most effective for system-wide recovery.
If the goal is to recover from user errors other workflows are more suitable.
Things like IDs in the database are not reserved and there is no guarantee that they are not reused after they have been removed; furthermore restoring data is an error-prone process that requires working directly with the database. This comes with unnecessary risks to the stability of the platform.

If we need some kind of recovery for users making mistakes then other approaches are available:
- Implement soft-delete (where data is marked as removed but not actually removed)
- Implement better confirmation dialogs, possibly requiring 4-eye principle 
- Implement better training

Soft-delete comes with other drawbacks since it would lock things like the token or the survey to that deleted project or workspace. We could of course remove that limitation and allow 2 projects to use the same survey & tokens.
