### ISSUE TITLE
Dashboard pages for individual services

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#395]
We still need to have a page for each service (i.e. ls question) for each sub category (current service pages / ls question groups)

**Comment by luna404** [comment]
@SamuelPetragallo I thought we decided to have a page for each service group with the ability to filter for one or multiple services within that group rather than to create individual pages for each service.

Rather than using the LS groups, I would propose to use the question codes themselves. This would also help to standardize the descriptive analysis I'm working on :)

- **General Clinical Services & Trauma Care**: Includes question codes starting with QHeRAMS1
- **Child Health & Nutrition**: Includes question codes starting with QHeRAMS2
- **Communicable Diseases**: Includes question codes starting with QHeRAMS3
- **STI & HIV/AIDS**: Includes question codes starting with QHeRAMS41
- **Maternal and Newborn Health**: Includes question codes starting with QHeRAMS42
- **Sexual Violence**: Includes question codes starting with QHeRAMS43
- **Non Communicable Diseases and Mental Health**: Includes question codes starting with QHeRAMS5

**Comment by SamuelPetragallo** [comment]
Yes I remember now the filtering, that's good with me, but we need to make sure this is
1. visible and easily accessible (we mentioned tabs I think?)
2. this is part of the PDF report download ;)
