### ISSUE TITLE
Data export (xlsx) for HeRAMS Yemen is missing on human resources and partner name if single-choice response is "other" and difficult to open in excel 

### ISSUE THREAD

**Issue by JeffDotingco** [HeRAMS-WHO/herams-backend#415]
Data export (xlsx) for HeRAMS Yemen is missing on:

- Human Resources (HFHR01_SQ006_SQ001, HFHR01_SQ002_SQ001, HFHR01_SQ003_SQ001, HFHR01_SQ004_SQ001, HFHR01_SQ005_SQ001, HFHR01_SQ001_SQ001). The responses are based on HFHR01 (requested by WHO YEM IM for automatic default zero response, no issue in downloading human resources part in LS)

- HFSUP3x1other if single-choice response of partner name (HFSUP3x1) is "Other" / "-oth-"

Exported data is also difficult to open in excel especially when text header=ON, answers as text, language=Arabic

![missing data on human resources and partner name of  other](https://user-images.githubusercontent.com/50957748/80506694-878e9180-89a8-11ea-99db-d3b136ad5a54.png)

**Comment by SamuelPetragallo** [comment]
@JeffDotingco could it be that Mustafa is changing the survey structure?
(@JeffDotingco go to bed!)

**Comment by SamuelPetragallo** [comment]
@luna404 could that be similar to the issue encountered by Mali on default answers in arrays?

**Comment by luna404** [comment]
I looked into the second issue on HFSUP3other and this seems to be related to the data refresh. 

Here are two examples: 
I donwload the csv in english from HeRAMs. These two records have "others" selected for HFSUP3 but don't have a value for "others.
![image](https://user-images.githubusercontent.com/18245059/80720106-bf0e5280-8afc-11ea-8e63-64eb09cf60bc.png)

If you compare this to LS, these two records indeed have a value for `HFSUP3x1other`.
![image](https://user-images.githubusercontent.com/18245059/80720886-d8fc6500-8afd-11ea-9959-9629721bdfc2.png)

The issue resolved itself after refreshing the workspace. 
![image](https://user-images.githubusercontent.com/18245059/80721864-0695de00-8aff-11ea-9302-e7722a7efff9.png)

So either there is an issue with the data refresh function or they are not saving the records but use `resume later`. I refreshed another random workspace and there seems to be quite a few records that are not up to date which might explain some of the data discrepancies.
![image](https://user-images.githubusercontent.com/18245059/80723172-94be9400-8b00-11ea-9633-3cd5e874ee82.png)

@SamMousa: Are both ls and HeRAMS using UTC? In the above examples, the timings seems interesting. If the 2h difference is because of UTC/ECT then it would mean the WS actually refreshed...


--

**Comment by SamMousa** [comment]
The server was using its local time; I have now updated LS configuration to use UTC.

**Comment by JeffDotingco** [comment]
For testing:
1. The dataset of HeRAMS YEM was downloaded from frontend (5,124 HFs)and the dataset from LS was also downloaded (7,362 HFs)
2. These datasets were merged using id as the identifier (I can only test/download 5124 HFs from staging)
3. I only tested the corresponding HF records from LS based on the HF record from staging.
4. The variables tested were human resources (HFHR01_SQ001_SQ001 - HFHR01_SQ006_SQ001) and health partner support (HFSUP3x1-HFSUP3x10).
5. Based on checking, all columns in human resources and health partner support have the same responses in frontend and LS.  


[HeRAMS_check.xlsx](https://github.com/HeRAMS-WHO/herams-backend/files/4687939/HeRAMS_check.xlsx)

**Comment by JeffDotingco** [comment]
Works on staging. Related to #428. Users with "Others" in HFSUP3x1 already have responses in HFSUP3x1other.

<img width="1680" alt="Screen Shot 2020-06-12 at 5 57 51 PM" src="https://user-images.githubusercontent.com/50957748/84491152-ae91f000-acd6-11ea-9764-fc27a597ee34.png">
