### ISSUE TITLE
Git Issues board for end users - ?

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#427]
Longer term: we need a way to capture suggestion, feature requests and manage those from end users

Short term: we'd like a solution like that to manage Yemen inputs

That definitely needs to be separate from dev discussions, but Git would probably be ideal.

Any idea @SamMousa ?

**Comment by SamMousa** [comment]
Github is not ideal for most users since everyone will need an account.
We could use something like this: https://www.opensupports.com/. Note that while I am generally in favor of open source, it might make more sense to go for a paid solution like Zendesk.

Since I'll be the one who has to manage self-hosted platforms, as well as provide support, having a paid platform means you do not have to rely on me for those tasks.

Let me know.

**Comment by SamuelPetragallo** [comment]
Agree that we need to think that more for the longer term but for now we'll only have 2 contributors for Yemen that's it and I don't foresee that to change for a while (as most other countries are happy with what we have). Would favor a space on git (we'll do the follow up with them on registration etc.)

**Comment by SamMousa** [comment]
You can create a separate repository for it.

**Comment by SamMousa** [comment]
Closed via https://github.com/HeRAMS-WHO/herams-support

@luna404 @SamuelPetragallo you are admins, if needed you can add others to it.
