### ISSUE TITLE
Increase visibility of "Sign up" to the platform

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#460]
Currently users are by default shown the login section.
The Sign up is not very visible. 

Could we, in the same space currently used for the login only have login and signup with the necessary fields and actions (and "password reset" too of course (though ok if that requires opening a new screen)?

@jeremiehelme

**Comment by jeremiehelme** [comment]
For now I've just added a text and a button to the request account page.
@SamMousa Is it possible to move the request account form to the login page ?
(what I've tried so far doesn't work)

**Comment by SamMousa** [comment]
Can you attach a rough mock up of what you want? After that assign it to me and I'll put in the rough structure.

**Comment by jeremiehelme** [comment]
Sure, 
Just adding the form to request an account under the login form that way would be great

<img width="1532" alt="Capture d’écran 2020-05-28 à 15 00 05" src="https://user-images.githubusercontent.com/2345926/83144648-f3713080-a0f3-11ea-8b0b-410d632960aa.png">

Then I'll probably make it slide left or right to display one or the other

Thanks,

**Comment by SamuelPetragallo** [comment]
Suggestion: instead of "Request account" I'd use "Register" on the action button as it feels more direct and reflective of the fact that there's not _granting_ of accounts, it's opened

**Comment by jeremiehelme** [comment]
Here is a better mockup of the idea
It hides the register form but increase readability, and I would say that the Register button is big enough not to be missed

the content would slide when clicking "Sign Up" or "Register"

![Capture d’écran 2020-06-03 à 15 22 26](https://user-images.githubusercontent.com/2345926/83641644-19904800-a5ae-11ea-8e62-16aeb06de952.png)

![Capture d’écran 2020-06-03 à 15 22 40](https://user-images.githubusercontent.com/2345926/83641654-1b5a0b80-a5ae-11ea-86fd-162b5285b69b.png)

**Comment by SamMousa** [comment]
I like that!

**Comment by SamuelPetragallo** [comment]
It's very nice yes (incl. the new icons etc.) well done!

Use wise I'd still prefer that both are fully visible from the start. 
Would that really squeeze it too much?

**Comment by SamMousa** [comment]
I think it's ugly and bad for the UX, most users don't need it and frankly, users who are not able to read  the word REGISTER at the top of a page will not be capable of data analysis in any capacity....

Why don't we try to solve the issue in smaller steps (ie the one proposed by @jeremiehelme ) instead of changing the whole UX based on feedback from computer-illiterate users?

**Comment by SamuelPetragallo** [comment]
It's the opposite, the aim here is to allow many more users register easily, not those that are already registered log in easily.

We are about to (pending senior management awakening) share our annual report to 4,500 people, we have just integrated HeRAMS to the internal emergency dashboard and will soon have it on the public facing dashbaord which is getting a lot of traffic and are making new connections with partners globally and in countries (GAVI, GF) etc.

I expect a lot of new users and don't want them to stumble on the first page

I don't see this as a major UX change and looked at all major website requiring accounts: the registration is in the majority of cases treated equally to the login if not more visible.

Can we see what this would look like?

**Comment by SamMousa** [comment]
> It's the opposite, the aim here is to allow many more users register easily, not those that are already registered log in easily.

Our users will log in 10s, possibly 100s of times. They only sign up once.

> I expect a lot of new users and don't want them to stumble on the first page

Honestly, how do we think people can use the platform if they can't read? How will they know how buttons work and where do we explain to them what a password is... 

> I don't see this as a major UX change and looked at all major website requiring accounts: the registration is in the majority of cases treated equally to the login if not more visible.

Users will read from top to bottom, having 2 forms one above the other will make it so that users start filling in the top one before seeing the other one.

The proposed design tackles this issue by showing the action you want to take first. If you really insist on having 2 forms on the same page, put them side by side and (re)move the introductory text. That will create for a more natural view where users can read both headers first and then decide which to form they must use.

**Comment by SamuelPetragallo** [comment]
Here's an ugly and imbalanced (towards new registration form) example:

![image](https://user-images.githubusercontent.com/15345099/83725893-ffed1000-a642-11ea-9506-c42824fea3f6.png)

Yet I don't get it wrong when I need to log in. Guess they prefer old users mistakenly filling the registration form (once) than new users stumbling on the login form.

Anyway, let's not loose too much time on this. I think we can look at what the form would look like (if you can provide that @jeremiehelme please) and take it from there

**Comment by SamMousa** [comment]
That's not that imbalanced; it shows 50% left **Recent logins** and 50% on the right **Create new account**

**Comment by SamuelPetragallo** [comment]
I meant the right side of the screen, where login occupies 10% (if not less) of the height. I never even realized the tiles were also entry point to login :)

Anyhow we need to be considering we're likely to get a lot of new users in the coming weeks, and not necessarily people that will submit or analyse data. Simply people that are curious to see what we work on. We also don't want to lose them ;)

**Comment by SamuelPetragallo** [comment]
(Normally such issues are better discussed around a beer... Git should really think about features that help recreate that kind of moments)

**Comment by jeremiehelme** [comment]
I agree with Sam, "Register" is understandable enough for a normal person, and most of the user are here to login. Hiding the registration form gives us space, which helps analyzing the page.  

However, since we know we will have a lot of new users coming to register, we could facilitate the registration process, for a limited period of time. 

Having the registration form directly available will encourage them to create an account, while not complicating the process too much for those who only need to login

When we decide the wave of new users is over, we can switch back to hiding the registration form  

<img width="1441" alt="herams-loginform" src="https://user-images.githubusercontent.com/2345926/83742813-266a7580-a65a-11ea-9863-d88b2ae6d1c4.png">

<img width="566" alt="herams-loginform-tablet" src="https://user-images.githubusercontent.com/2345926/83742823-29656600-a65a-11ea-8e0f-4d9a90513369.png">

**Comment by SamMousa** [comment]
Make sure it works properly for password managers too please. They can get confused

**Comment by SamuelPetragallo** [comment]
Thanks folks, I like the initial design/flow very much, and yes, this may be temp.
I'd personally go for the first design (same as current both forms on the right side).
I'll look at reworking the welcome text too

**Comment by jeremiehelme** [comment]
Changed spacing and font sizes to have a smaller popup

![Capture d’écran 2020-06-12 à 16 14 55](https://user-images.githubusercontent.com/2345926/84512194-e47ba800-acc7-11ea-8d11-627aaacd27a9.png)

**Comment by SamuelPetragallo** [comment]
Layout breaks in Firefox and doesn't allow registration at all

**Comment by SamuelPetragallo** [comment]
> Layout breaks in Firefox and doesn't allow registration at all

Due to old (non updatable) WHO version of Firefox

![image](https://user-images.githubusercontent.com/15345099/84514896-0b3bdd80-accc-11ea-94e7-119cc597d299.png)
