### ISSUE TITLE
Registration bugs

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#502]
When hitting "Register" on staging:

![image](https://user-images.githubusercontent.com/15345099/84513654-0d9d3800-acca-11ea-88dc-a923ee65ae5d.png)

(Sorry if cross-posting I thought this was looked at but seems we've confused different bugs)

**Comment by SamMousa** [comment]
I'm not sure who is in control of Herams.org, but I am not.

**Comment by SamMousa** [comment]
This could also just be because the staging server is not allowed to send mail from the prod domain. In which case it wouldn't be an issue on PROD.
I expect this is the case, the error you see doesn't actually come from our code.

**Comment by SamuelPetragallo** [comment]
So how do we go about that?

**Comment by SamMousa** [comment]
> So how do we go about that?

We accept that there is a difference between prod and staging. Reality is that fixing this doesn't give us any guarantees for PROD. These errors are thrown by external services because our staging server is not allowed to send mail from the herams.org domain, which makes sense for security.
Fixing it would mean that we change the sender to something like `platform@herams-staging.org`, but even if that works it doesn't provide us with any guarantees about sending emails from PROD.

So this is a bug, and it hampers testing some use cases on staging; but because of the reasons outlined above I do not think it should be a blocker.

**Comment by SamMousa** [comment]
Sending mail from staging is bugged, this does not affect PROD.
