### ISSUE TITLE
Charts : Extract legend

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#508]
Extract the legend from the charts to html, in the dashboard, elements and PDF export

Related to #433 and #421

**Comment by luna404** [comment]
The new html legend seem to only support one column. This results in charts requiring a huge amount of space in order to avoid overflowing the element container. Would it be possible to have multiple columns if the legend as more than x number of legend elements?

![image](https://user-images.githubusercontent.com/18245059/85373850-290f0b00-b534-11ea-9cb0-8e0f6fd8ef18.png)
https://herams-staging.org/project/24?page_id=279
![image](https://user-images.githubusercontent.com/18245059/85374017-696e8900-b534-11ea-842b-d2b094c65b74.png)

**Comment by jeremiehelme** [comment]
Exact, fixed it yesterday, but never clicked the merge button. Should be good in a few minutes

**Comment by luna404** [comment]
Also the legend interferes with the hover-over pop-ups
![image](https://user-images.githubusercontent.com/18245059/85374506-2e208a00-b535-11ea-8932-c3b25da0d20a.png)

**Comment by jeremiehelme** [comment]
Added columns, and improved tooltip display by rendering them in html as well
