### ISSUE TITLE
Localhost : Missing secret, hmacParam, paramsParam and expirationParam

### ISSUE THREAD

**Issue by jeremiehelme** [HeRAMS-WHO/herams-backend#518]
Since rebuilding the containers, the tests fail because secret, hmacParam, paramsParam and expirationParam are missing
I can't remember if and how we set them up the first time...
Where can I find these ?

Thanks,

**Comment by SamMousa** [comment]
I can't remember either; these are things you should be able to figure out yourself @jeremiehelme, I don't want to be your tech support every time you break your local development environment.

Have a look at the source code causing the error and you will find which of those variables you mention is actually coming from the environment. Then replace it with a different value.

And write these things down so you can look it up next time. There has been no changes to this part so I think you've just deleted some files locally causing this issue.

**Comment by jeremiehelme** [comment]
Thanks Sam, be sure I figure things out by myself as much as possible before asking, I know you have better things to do. They seemed important variable so thought I'd rather ask

**Comment by SamMousa** [comment]
> be sure I figure things out by myself as much as possible before asking

Well for one, looking at the code you could have seen that most of the variables you mentioned are actually in the config, so there is just 1 missing, which is the secret.

Looking at the README in this repo one of the steps is `cp .env.default .env` which copies placeholder values.
This leads me to believe that you no longer have a `.env` file (probably because you removed it).

Furthermore just searching for `URL_SIGNING_SECRET` in the code base would have at least led you to the `.env.default` file which contains it..

Every time you ask these kinds of questions I go through the exact same process you should be going through, I do not remember these things or know them by heart. And every time you ask me you don't learn to figure it out for yourself...
