### ISSUE TITLE
Access to ls is down/problematic

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#575]
Different issues as of yesterday:

1. field colleague from Yemen:
![image](https://user-images.githubusercontent.com/15345099/90362092-114d9200-e060-11ea-86ee-80d6e7199f94.png)

2. I myself got an itnernal server error yeterday before being allowed in ls

3. this morning I was directed to the login page (not loged in straight as usual)
![image](https://user-images.githubusercontent.com/15345099/90362162-3d691300-e060-11ea-9fd4-61a395abf1c1.png)

**Comment by luna404** [comment]
To add to Sam's comments, I get an internal server error when I try to login 
![image](https://user-images.githubusercontent.com/18245059/90363020-2cb99c80-e062-11ea-8a75-47a73b1ab0f1.png)

Also, their training started at 8am so they would ideally need this before 10am.

**Comment by SamMousa** [comment]
I have cleaned the session files, it should work again now.

**Comment by luna404** [comment]
Thanks, as we seem to have recurring issues like this, and the solution is just deleting temp or session file, can someone else on the team be trained to resolve these so we avoid a bottleneck of only @SamMousa being able to do this?

**Comment by SamMousa** [comment]
Honestly, I don't think so.
The solution is simple, but as identifying the issue is not as simple. (As is evidenced by the fact that the initial conclusion yesterday was "LS is down")

The permissions needed on the server to do the needed operations make it risky for someone not knowing what they are doing.
Note that this is something we can fix (the automated session cleanup seems not to be working), so this will be something to look at when I'm back.
