### ISSUE TITLE
Response picker: filter not working for Yemen

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#608]
Filtering responses doesn't seem to work for Yemen, but it does work for other projects.

Yemen: https://herams.org/workspace/7690/limesurvey
BF: https://herams.org/workspace/7104/limesurvey

**Comment by jeremiehelme** [comment]
Seems related to when you choose columns to be displayed only in the responses, it shifts the filters.
I'm on it

**Comment by jeremiehelme** [comment]
Ok, the filtering functionality of Datatables is not working properly when you hide columns.
When a hidden column is at the left of a visible column, the filter of the visible column applies to the previous visible column, which is a bug 

I moved all the hidden columns (that should only be displayed in the responses) to the right, so that it doesn't mess with the filtering

To test 
Yemen : https://ls.herams.org/survey/index/sid/618734/token/l5mPbyBaVVbeaAd1/newtest/Y/lang/fr-FR?test=ResponsePicker
BF : https://ls.herams.org/survey/index/sid/341175/token/OJL6sjv6PEF7WcO/newtest/Y/lang/fr-FR?test=ResponsePicker

**Comment by luna404** [comment]
Not sure I fully understand what the issue was, but seems to be working in the two examples you gave.
