### ISSUE TITLE
API for end-user to download project level data

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#649]
Develop an api allowing external users to automate downloading a csv export of project level data

**Comment by luna404** [comment]
We have pending requests from YEM, BF, and SD for this.

**Comment by SamMousa** [comment]
Can you define how you would format the data?
Specifically, multiple choice & ranking need to be explicitly defined.
Since we'll switch survey backend it is important that this is properly defined so that we can maintain compatibility for the future.

Also before we release this I think we should properly define how we will handle changes to the API. If we don't do this in advance I'm very worried that we'll be stuck with a piece of code that can never change because our API consumers won't be able to deal with it.

**Comment by luna404** [comment]
`Can you define how you would format the data?` 
Ideally the format should be the same as in the csv export. So multiple choice and ranking questions would be split into multiple fields.

`Also before we release this I think we should properly define how we will handle changes to the API`
Do you have any suggestion on how this should be done?

Another point that needs further discussion is permissions/access to the data. Not all users should be able to pull all variables. E.g. we need a way for variables to be marked as confidential so they will not appear in the default export. This is particularly important for personally identifiable information such as contact details of respondents.

**Comment by SamMousa** [comment]
> Ideally the format should be the same as in the csv export. So multiple choice and ranking questions would be split into multiple fields.

How? There are multiple ways to do this.

> Do you have any suggestion on how this should be done?

There should be a grace period that we commit to, so we mark an API as deprecated for a period of time before we actually remove / break it.
A simple approach would be something like this:
- If an API is deprecated our responses will have a header like `X-Deprecated-Since: 2020-11-16`
- After the grace period has expired we are free to remove or break that API

All consumers must agree that they will not (attempt to) delay this process since it will make us a hostage of their processes.

> Another point that needs further discussion is permissions/access to the data. Not all users should be able to pull all variables. E.g. we need a way for variables to be marked as confidential so they will not appear in the default export. This is particularly important for personally identifiable information such as contact details of respondents.

In SurveyJS we can add a field to each question to mark it as personal data, one could even argue that this personal data should never be there in an export since it serves no value for analysis.

**Comment by luna404** [comment]
`How? There are multiple ways to do this.`
Can you give me an example?

`All consumers must agree that they will not (attempt to) delay this process since it will make us a hostage of their processes.`
Does this matter if we can just remove it after the grace period has expired?

`In SurveyJS we can add a field to each question to mark it as personal data, one could even argue that this personal data should never be there in an export since it serves no value for analysis.`
Great and agree for confidential data. There will however be other, more country specific challenges such access to coordinates.

**Comment by SamMousa** [comment]
> Can you give me an example?

Multiple choices A, B could be exported as boolean columns, one column for each option. Or as a number of choice columns containing the value of the choice (so the number of columns will depend on the max number of choices chosen in a single response)
Same for ranking.

> Does this matter if we can just remove it after the grace period has expired?

Yes because otherwise they will start crying and it will go up the chain of command and we'll then be told that we can't remove it because some country that is very important is depending on this but won't have time to update their API usage until 2025..

> There will however be other, more country specific challenges such access to coordinates.

We should tackle those separately, so we have non-analytical data, for that a simple solution like "never export" works.

For data that is used in analytics like GPS we would need permissions, but that makes it way more complicated and is actually not something we can do now. Note that the maps also show all this data and it can easily be extracted from there.
In my opinion we should not support this use case; if you have access to read the project dashboard you have access to all coordinates anyway, so that should be the level where we decide that.
If we need more control that's a separate issue and it would be a bigger one.

**Comment by luna404** [comment]
`Multiple choices A, B could be exported as boolean columns, one column for each option. Or as a number of choice columns containing the value of the choice (so the number of columns will depend on the max number of choices chosen in a single response)`
I would prefer the second option so we keep as close to the current export as possible.

`All consumers must agree that they will not (attempt to) delay this process since it will make us a hostage of their processes.`
We can build this into the data request from that we are currently working on. This means user will have to agree to this before getting access to the data. This should be enough I hope.


`For data that is used in analytics like GPS we would need permissions, but that makes it way more complicated and is actually not something we can do now. Note that the maps also show all this data and it can easily be extracted from there.
In my opinion we should not support this use case; if you have access to read the project dashboard you have access to all coordinates anyway, so that should be the level where we decide that.
If we need more control that's a separate issue and it would be a bigger one.`
Noted. We can take this one later if needed.

**Comment by SamMousa** [comment]
> I would prefer the second option so we keep as close to the current export as possible.

This shouldn't be an argument it should be the best format not the format that we have now for some reason.. As far as I know analysis is easier if you have a column for each choice containing `true / false` depending on if it was picked.

**Comment by SamMousa** [comment]
Option: temp api for @luna404

**Comment by SamuelPetragallo** [comment]
Decision for now:

1. temp api for admin dashboard (@luna404 )

2. other specific needs on standby (manual data downloads for now)

3. longer term (after migration to SurveyJS)
a. terms of us should clearly indicate conditions (and the fact that the API may be deprecated unilaterally after notification and after a pre-defined period)
b. means we need to be able to track/contact FPs in charge of APIs easily to notify them
c. period between notification and deprecation should be 6 months
d. after 6 months the API should effectively be deactivated
c. internally, deprecation may actually happen after 9 months (to avoid heavy reverse engineering)
