### ISSUE TITLE
Admin page: No workspace access without edit permissions

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#771]
Users who don't have edit permissions to a workspace are not able to open the workspace.

E.g. A user you could only be granted permissions to download data without having edit right. In this case the users would still need to be able to open the workspace and view the "Export" tab.

**Comment by SamMousa** [comment]
This is an issue with how navigation is set up.
The entry page for a workspace is now always the facilities list (as per the navigation redesign)..

Could we show the list, but not allow people to actually edit the response?

**Comment by SamuelPetragallo** [comment]
Yes, the impossibility to have a view only on response was one of the limitations of RespPicker.
Think we should have that as we move away from ls

**Comment by SamMousa** [comment]
Again like other features, can now implement it in an insecure manner, so we hide it visually until we move away and do it properly

**Comment by SamMousa** [comment]
If we do implement it, does that mean we're okay to show the facility list if users can only download data? -- I'd intuitively say yes, because the data also contains the list

**Comment by SamuelPetragallo** [comment]
Not sure it's urgent - so defer to @luna404 on whether to do it now or later.

Longer term implementation this should be de-linked from the ability to download data: we may want to allow users see who is managing what without necessarily allowing further access to the data (the list only shows a minimal number of variables)

**Comment by SamMousa** [comment]
It is linked to downloading data

**Comment by luna404** [comment]
`If we do implement it, does that mean we're okay to show the facility list if users can only download data? -- I'd intuitively say yes, because the data also contains the list`

Yes, the whole purpose of the download in these cases is so users can have view access without being able to edit the data.

**Comment by SamuelPetragallo** [comment]
Longer term we'll want to allow users see "who manages what" in terms of HFs without allowing download (especially if download provides all variables - same rational as seeing the Project and WS lists

**Comment by SamMousa** [comment]
> Longer term we'll want to allow users see "who manages what" in terms of HFs without allowing download (especially if download provides all variables - same rational as seeing the Project and WS lists

I like how you casually insert something very complicated here... Managing individual variables is not really feasible since the variables themselves are also dynamically defined in the survey. Since we will also support multiple surveys per HF, it makes more sense to manage this at the survey level than at the variable level.

@luna404 I have now updated the response picker to dynamically hide the update & delete button based on user permissions as well. These are not yet configurable in such a detailed level in the platform though.
For now "manage data" means you can see edit & delete buttons, (and for create we'll have the custom logic already discussed).

If you can download data but not manage you'll see a list of HFs and responses, but not the buttons for editing / deleting.

**Comment by SamuelPetragallo** [comment]
:) not sure I've expressed things clearly actually: what I meant is to have a permission that allows users to view the list of HFs managed in a given WS - ?

**Comment by SamMousa** [comment]
I don't know what you mean here...

Let's create a new issue when we get to that, it's not related to this issue.

**Comment by SamuelPetragallo** [comment]
Similar to view permission on a project which allows me view the list of WSs.
View permission on a given WS allows me view the list of HF managed within that WS
I can create a new issue if relevant

**Comment by SamMousa** [comment]
I don't think it is relevant, since what we @luna404  and I discussed just above here is that this permission is not needed since anyone who can do anything in the workspace is allowed to just view the list...  Since that is the only way they can get to things like exporting since they need to use the tabbed navigation...

**Comment by SamuelPetragallo** [comment]
I was thinking of the case where we don't want to grant other permissions than this view permission
