### ISSUE TITLE
Response tab should only be visible for global admins

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#792]
Only global admins currently have permissions to view the responses but the icon/tab is visible to any user having been granted permissions to manage workspaces. If they try to open a response they get an error "Your are not allowed to perform this action".  
Would it be possible to hide the tab for all users but global admins?

e.g. https://herams-staging.org/response/136446/compare?survey_id=618734

**Comment by joester89** [comment]
I did not filter on milestones properly so already picked this one up.

- Changed to only **show** the responses tab to global admins, did not add permission check to the page itself
- Changed the name of the export permission to "Export data" instead of "Download" to make it more consistent with the tab names
- Made the response compare page a little more fancy (please check if this works for you)

**Comment by luna404** [comment]
`Made the response compare page a little more fancy (please check if this works for you)`
Thanks for this. I didn't wonna add as an issue as I'm the only one using this page. But looks much better now.
