### ISSUE TITLE
Project/Workspace responsible

### ISSUE THREAD

**Issue by joester89** [HeRAMS-WHO/herams-backend#806]
- [x] New permission "Lead" (Project lead/Workspace lead)
- [x] Show who is responsible
- [ ] ~~Having the "Lead" permission also means you can grant access~~

Questions @luna404:
- Where do we want to show who is the "Lead"?
- What wording do we want to use for the "Lead"?
- Does the "Lead" permission imply Admin permission? (Otherwise a "Lead" cannot grant all permissions)

**Comment by luna404** [comment]
`Where do we want to show who is the "Lead"? `
- I would have liked it to be in the workspace/project as a "contact" tab or something like that, but as users can only access a workspace/project if they have permissions, I think the only place we can put it is in the list of workspaces/projects (e.g. https://herams-staging.org/project/13/workspaces for workspace leads and https://herams-staging.org/project/index for projects leads)  

`What wording do we want to use for the "Lead"?`
`Workspace owner` for workspace leads and `Project admin`. @SamuelPetragallo should we have a separate label for `project owners`?

`Does the "Lead" permission imply Admin permission? (Otherwise a "Lead" cannot grant all permissions)`
I don't think that's a problem and I know @SamuelPetragallo doesn't like to bundle permissions ;)

**Comment by joester89** [comment]
@luna404 I made a basic first implementation and it is on staging:
- on `/project/index` and `/project/{id}/workspaces` there now is a column `Lead`
- on `/project/{id}/share` and `/workspace/{id}/share` there now is the possibility to assign the permission `Lead`
- the permission `Lead` implies the permission `Admin` on either a project or workspace

Questions:
- Is the naming `Lead` fine?
- Is only showing the name sufficient?

**Comment by SamuelPetragallo** [comment]
That's fast - loving it :)

On labelling, we need:
1. Workspace owners
2. Project coordinator (I don't think we need a "label" for the Project administrator as he would not need to be identified/contacted personally)

And yes, I'd rather not bundle permissions so we remain as flexible as possible: i.e. we can still decide depending on the skills of each individual and incrementally assign new permissions as required

This specific "permissions" (since it's managed like this) will mean these individuals are the point of contact for projects / WSs - no more

**Comment by joester89** [comment]
@SamuelPetragallo, I do not really understand 2.

I have 1 role (permission) that is applied on either the Workspace or Project. In the share view the label will be shared between both entities.

The only difference I can make is in the list views, there the column header can differ.

I will change the role to actually nog give any permissions.

**Comment by SamuelPetragallo** [comment]
Yes there are indeed only 2 roles to be highlighted: the first one at WS level ("Workspace owner") the second one at project level ("Project coordinator").

Can labels in the share view not be contextualized to the object we're sharing permissions on (Project vs WS)?

**Comment by joester89** [comment]
After some research I found that was possible :)

The correct labels are now on staging as well.

One more question: Is it correct that a "Project coordinator" should also show up on all workspaces within that project as "Workspace owner"(, like I did now)?

**Comment by SamuelPetragallo** [comment]
Great thanks!

On your question: no, Project coordinator will (most likely) have all permissions on WSs - but should not show as WS Owner (unless explicitly assigned)
