### ISSUE TITLE
Create new HF permission should not be part of manage workspaces

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#819]
For projects with edit ≠ create, the `manage workspaces` permission includes the permission to create new HFs. I find this confusing and would prefer if the create HF is not included in the bundle of permissions.

**Comment by SamMousa** [comment]
What do you mean by 
> edit ≠ create,

?

**Comment by luna404** [comment]
Projects for which `Manage data implies creating facilities` is disabled

**Comment by SamMousa** [comment]
I'm not able to reproduce this and also not fully clear on what you mean. As far as I can tell you're basically saying this feature does not work at all.
Since if the setting is enabled we would expect this behavior... So state your preference as something subjective makes no sense to me.

Can you provide a specific example?

**Comment by SamMousa** [comment]
After some more research I think there is confusion on which permission should imply the create HF permission.
It was my understanding that the base permission was `manage workspaces`, but you seem to want it to be `edit data`?

**Comment by luna404** [comment]
Yes, the base permission should be edit. 
By default, all users who have edit permission should have permission to create a new health facility. 
If this is disabled at the project level, create should not be included in either the edit or manage workspace permissions but should only be granted if explicitly granted.
