### ISSUE TITLE
Filters - search field doesn't seem to be responding

### ISSUE THREAD

**Issue by SamuelPetragallo** [HeRAMS-WHO/herams-backend#834]
For example tried typing "rehab" for Tigray - https://herams.org/project/46 - and got no return (while the term is found in filters)

**Comment by luna404** [comment]
It is working, just not as expected :)

Issue 1: The **Date** group/question is always displayed, regardless of what the user is searching for.

Issue 2: The filter currently only works for group headers but not for individual questions. This should be changed so that users can filter for specific questions.

Issue 3: For some keywords (e.g. if you search for "health"), the filter is working, but it displays all questions in a group rather than just the ones meeting the search criteria. In the example below only the question in yellow should be returned. 
![image](https://user-images.githubusercontent.com/18245059/114710562-c5a1d400-9d25-11eb-9736-5a0798d046ed.png)

**Comment by joester89** [comment]
Can be tested in https://feature-349-request-access.herams-staging.org

**Comment by LuciannaFG** [comment]
Hi all. I tested the "Request Access" and this error message appeared: 

![Error msg to the request access test 10_06_2021](https://user-images.githubusercontent.com/36709188/121517674-f03f9e80-c9ef-11eb-9786-850db9727d24.png)
