### ISSUE TITLE
Disable health facility temporarily 

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#842]
It should be possible to mark a health facility as "temporarily inaccessible/not functioning". The goal would be that once the facility becomes "active" again, the user can reactivate it rapidly without having to re-answer all other questions again. 

Related to #840

**Comment by SamuelPetragallo** [comment]
We just discussed that in the weekly and some of the implications. These mainly arise from the need we would then have to systematically describe the rules that apply to the dataset: currently, we don't have to bother as the absence of data (determined by the survey logic itself) leads to the exclusion of a given record. Keeping all data, would mean we'd need to inform the system on when to keep/exclude records for each individual dashboard page or even chart/map in some cases, but also for data exports and related (API).

I suggest we rediscuss this together in early sept. If I recall correctly this is related to the annual mobile clinics we found out about in M. Since this is a rather unusual 7 rare use case we may want to reconsider the approach.

The discussion also brought some interesting ideas, incl. the possibility to define custom filters for individual dashboard pages and raised the need to better describe those filters (regardless of whether they are custom or systematic) - similar to the interpretation guide developed for the SBRs
