### ISSUE TITLE
Dashboard bar charts improvements

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#871]
Can we make a few improvements to the bar charts? 

![image](https://user-images.githubusercontent.com/18245059/124246029-d42baa80-db20-11eb-973d-a045d4097d0f.png)

- The total label should be moved outside the plot area. Depending on the data, it currently overlaps with the bars. This is the main reason why we're currently not using these charts.

Optional improvements:
- Increase space between plot and legend
- Increase plot width based on the number of bars
- Order bars in descending order.

**Comment by luna404** [comment]
Example: 
https://feature-349-request-access.herams-staging.org/project/1?page_id=79
https://feature-349-request-access.herams-staging.org/element/262/update

**Comment by joester89** [comment]
@luna404 I looked into the possibilities:
- Move total label out of plot area, this is going to be a challenge since it is generated and rendered by the chart. So for now there are two options: easy -> remove total count in case of a bar chart, medium -> locate it in the top right corner (which should be way safer when ordering the bars)
- Increase space between plot and legend, easy, will add in 10px of spacing
- Increase plot width based on the number of bars, won't look into this for now. The chart sizes are standardised to make sure it works within the dashboard and I don't want to mess with that.
- Order bars in descending order: can do easily

An image to indicate the spaces available:
![image](https://user-images.githubusercontent.com/9624366/124599714-432d3a00-de66-11eb-9214-d7a3d1043f57.png)

**Comment by luna404** [comment]
I would go for option 2 on the total labels (i.e. move it to the top right corner.)
All fine for the other points.
