### ISSUE TITLE
Project settings - languages

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#890]
I have a few questions regarding the new language options in the project settings (e.g. https://herams-staging.org/project/28/update)

1. The checkboxes are for the survey languages used in the MHFL while the I18n Titles are the project titles. Is this correct? 
2. Why do we have English as a translation option for the titles? Shouldn't this be the default title? 
3. Can we change the title I18n to "Project title translations" or something else more easily understandable. 
4. Can we remove Dutch as an option? Unless you would like to do the translations for it :).

**Comment by SamMousa** [comment]
1. Yes
2. This was already fixed
3. I have changed it to `Active Languages` and added a hint:
![image](https://user-images.githubusercontent.com/547021/141473999-9af1674b-e5bf-48cb-bbcb-df3e2fc3dc0c.png)


4. Done

Could we not fully remove this option and always make all languages available? Since we will have admin survey at the facility level only people who understand the system will be using the admin survey & editing workspace / project settings..

**Comment by SamMousa** [comment]
@luna404 I have assigned this to you mainly for my last question; if you prefer to leave the option in then just close this :)
