### ISSUE TITLE
Add workspace name to dashboard filters

### ISSUE THREAD

**Issue by luna404** [HeRAMS-WHO/herams-backend#958]
How much work would be to add the workspace name as a filter option in the dashboard filters 

https://herams.org/project/59#
![image](https://user-images.githubusercontent.com/18245059/146021918-e658dbe5-2473-4630-bc97-da4d59b811f9.png)

@joester89  as you were looking for small issues for next week, would this be something doable as your last issue? - It would make a lot of people very happy.

**Comment by joester89** [comment]
(did not research yet if this is easily do-able)

How would you want the search to work:
1. a multi select with the available workspace names: you type and it autocompletes the available workspaces and you can select one or multiple and the filter is applied with those workspace id's
2. you just type a string and the workspaces in the project are filtered by the fact that they contain (or start with?) this string

While typing this I would recommend option 1, since that way it is clear what the filter does. The second option leaves it kind of vague what actually is filtered on.

**Comment by luna404** [comment]
Option 1 would be preferable. This would also mean it's in line with the other filters which makes it easier for users.

**Comment by joester89** [comment]
It can now be tested at https://feature-958-add-workspace-filter.herams-staging.org/ :)

**Comment by joester89** [comment]
It I also fixed #954 and made the filters button the same size as the rest ;)
